# Development Configuration
spring:
  config:
    activate:
      on-profile: dev

  # Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:network_twin_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  # JPA/Hibernate Configuration for Development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  # Logging Configuration for Development
  logging:
    level:
      com.network.digitaltwin: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration for Development
jwt:
  secret: devSecretKeyForDevelopmentOnly
  access-token-expiration: 3600000  # 1 hour
  refresh-token-expiration: 604800000  # 7 days
